@port = 3000
@api = http://localhost:{{port}}

GET {{api}}/videos

### Los id deben tener 24 chars, de otro modo no funciona
GET {{api}}/videos/6031d71e980aad29480d88fd

### CREATE A VIDEO
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=uJ_1HMAGb4k",
    "title": "Riptide",
    "author": "Vance Joy"
}

###
DELETE {{api}}/videos/1

###
PUT {{api}}/videos/1