@port = 3000
@api = http://localhost:{{port}}

GET {{api}}/videos

### Los id deben tener 24 chars, de otro modo no funciona
GET {{api}}/videos/6031e46e0a417a23746a783a

### CREATE A VIDEO
POST {{api}}/videos
Content-Type: application/json

{
    "url": "https://www.youtube.com/watch?v=uJ_1HMAGb4k",
    "title": "Riptide",
    "author": "Vancy"
}

###
DELETE {{api}}/videos/6031e46e0a417a23746a783a

###
PUT {{api}}/videos/6031e46e0a417a23746a783a
Content-Type: application/json

{
    "author": "Vance Joy"
}